### ISSUE TITLE
No internet connection after doing your tutorial with pi, Tor and raspap

### ISSUE THREAD

**Issue by masterdot** [fire1ce/3os.org#9]
Thank you for your halp in advance,

everything seems to run fine, but I don't have a internet connection. 

I want eth0 be the source and wlan0 to be the Tor AP. I think I missed something, but I don't find the reason. Hope you don't mind this kinda contact :)

**Comment by fire1ce** [comment]
hey, i've deprecated the guide. Use https://www.torbox.ch/
